
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: postgresql
    # you might want to remove ports section if you don't need to manage postgres outside
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - spherumcommon
  java1:
    image: medianik5/spherum
    container_name: java1
    ports:
      - "8080:8080"
    networks:
      - spherumcommon
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/postgres
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.flyway.url=jdbc:postgresql://postgresql:5432/postgres
      - spring.flyway.user=user
      - spring.flyway.password=password


networks:
  spherumcommon:
    driver: bridge
