CREATE TABLE "users"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    balance         DECIMAL(12, 2) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE "books"
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price   BIGINT NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE "book_item"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id BIGINT NOT NULL,
    amount  BIGINT NOT NULL,
    CONSTRAINT pk_bookitem PRIMARY KEY (id),
    CONSTRAINT FK_BOOKITEM_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id)
);

create table users_books(
   users_id bigint not null,
   books_id bigint not null,
   constraint FK_USERBOOKITEM_ON_USER foreign key (users_id) references users (id),
   constraint FK_USERBOOKITEM_ON_BOOKITEM foreign key (books_id) references "book_item"(id)
)